In [7]:
import sys
from pathlib import Path
from typing import cast

import numpy as np
import pandas as pd
from scipy.stats import spearmanr
from IPython.display import display


# ============================================================
# Projektpfad und eigene Utilities
# ============================================================

project_root = Path.cwd().parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from utils.saving_utils import DatasetBundle


# ============================================================
# Vollständige Discovery- und Validation-Datensätze laden
# ============================================================

data_discov_full = DatasetBundle.load(
    project_root / "data" / "preprocessed" / "data_discov_full"
)

data_valid_full = DatasetBundle.load(
    project_root / "data" / "preprocessed" / "data_valid_full"
)

data_discov_full.meta = cast(
    pd.DataFrame,
    data_discov_full.meta
)

data_valid_full.meta = cast(
    pd.DataFrame,
    data_valid_full.meta
)


# ============================================================
# Clusterlabels und Posterior-Wahrscheinlichkeiten laden
# ============================================================

proba_and_labels_discov = pd.read_parquet(
    project_root
    / "outputs"
    / "gmm_clustering"
    / "cluster_pred_discov.parquet"
)

proba_and_labels_valid = pd.read_parquet(
    project_root
    / "outputs"
    / "gmm_clustering"
    / "cluster_pred_valid.parquet"
)

proba_discov = proba_and_labels_discov.drop(
    columns="label"
)

proba_valid = proba_and_labels_valid.drop(
    columns="label"
)

labels_discov = proba_and_labels_discov["label"]
labels_valid = proba_and_labels_valid["label"]


# ============================================================
# Surveygewichte
# ============================================================

sample_weight_discov = (
    pd.to_numeric(
        data_discov_full.data["wichtn"],
        errors="coerce"
    )
    .to_numpy(dtype=float)
)

sample_weight_valid = (
    pd.to_numeric(
        data_valid_full.data["wichtn"],
        errors="coerce"
    )
    .to_numpy(dtype=float)
)


# ============================================================
# Gespeicherte Cluster-Summaries laden
# ============================================================

summaries_folder = (
    project_root
    / "outputs"
    / "gmm_clustering"
)

cluster_discov_summaries = pd.read_parquet(
    summaries_folder
    / "cluster_discov_summaries_not_nominal.parquet"
)

cluster_valid_summaries = pd.read_parquet(
    summaries_folder
    / "cluster_valid_summaries_not_nominal.parquet"
)


# ============================================================
# Cluster-ID als Index setzen
# ============================================================

cluster_discov_summaries.index = pd.Index(
    range(len(cluster_discov_summaries)),
    name="cluster"
)

cluster_valid_summaries.index = pd.Index(
    range(len(cluster_valid_summaries)),
    name="cluster"
)


# ============================================================
# Plausibilitätsprüfungen
# ============================================================

if len(labels_discov) != len(data_discov_full.data):
    raise ValueError(
        "Discovery-Labels und Discovery-Daten haben "
        "unterschiedliche Längen."
    )

if len(labels_valid) != len(data_valid_full.data):
    raise ValueError(
        "Validation-Labels und Validation-Daten haben "
        "unterschiedliche Längen."
    )

print(
    "Discovery:",
    len(data_discov_full.data),
    "Personen,",
    labels_discov.nunique(),
    "Cluster"
)

print(
    "Validation:",
    len(data_valid_full.data),
    "Personen,",
    labels_valid.nunique(),
    "Cluster"
)

print(
    "Discovery-Summaries:",
    cluster_discov_summaries.shape
)

print(
    "Validation-Summaries:",
    cluster_valid_summaries.shape
)

Loaded dataset from /Users/aginatore/Desktop/Consulting/esa_consulting/data/preprocessed/data_discov_full.
Loaded dataset from /Users/aginatore/Desktop/Consulting/esa_consulting/data/preprocessed/data_valid_full.
Discovery: 8835 Personen, 23 Cluster
Validation: 8588 Personen, 23 Cluster
Discovery-Summaries: (24, 214)
Validation-Summaries: (24, 214)

In [13]:
data_discov_full = DatasetBundle.load(
    project_root / "data/preprocessed/data_discov_full"
)

data_valid_full = DatasetBundle.load(
    project_root / "data/preprocessed/data_valid_full"
)

data_discov_full.meta = cast(
    pd.DataFrame,
    data_discov_full.meta
)

data_valid_full.meta = cast(
    pd.DataFrame,
    data_valid_full.meta
)

Loaded dataset from /Users/aginatore/Desktop/Consulting/esa_consulting/data/preprocessed/data_discov_full.
Loaded dataset from /Users/aginatore/Desktop/Consulting/esa_consulting/data/preprocessed/data_valid_full.

In [14]:
# ============================================================
# 1. Kontinuierliche und ordinale Variablen auswählen
# ============================================================

profile_variables = (
    data_discov_full.meta
    .loc[
        lambda df: df["type"].isin(["continuous", "ordinal"]),
        "name"
    ]
    .tolist()
)

print(
    f"Laut Metadaten ausgewählt: "
    f"{len(profile_variables)} kontinuierliche/ordinale Variablen"
)

import ast


# ============================================================
# 2. Gewichtete Clustermittelwerte aus den Summaries holen
# ============================================================

def extract_mean_columns(summary):
    """
    Extrahiert Mittelwertspalten aus einer Cluster-Summary.

    Erwartet Spaltennamen wie:
    "('alter', 'mean')"
    "('alter', 'std')"
    """
    summary = summary.copy()

    parsed_columns = {}

    for column in summary.columns:
        try:
            variable, statistic = ast.literal_eval(str(column))
        except (ValueError, SyntaxError, TypeError):
            continue

        if statistic == "mean":
            parsed_columns[column] = variable

    if not parsed_columns:
        raise ValueError(
            "In der Cluster-Summary wurden keine "
            "Mittelwertspalten gefunden."
        )

    result = summary.loc[:, list(parsed_columns)].copy()
    result = result.rename(columns=parsed_columns)

    return result


disc_cluster_means_all = extract_mean_columns(
    cluster_discov_summaries
)

valid_cluster_means_all = extract_mean_columns(
    cluster_valid_summaries
)

# Numerisch konvertieren
disc_cluster_means_all = disc_cluster_means_all.apply(
    pd.to_numeric,
    errors="coerce"
)

valid_cluster_means_all = valid_cluster_means_all.apply(
    pd.to_numeric,
    errors="coerce"
)

# Gewichtungsvariable entfernen
disc_cluster_means_all = disc_cluster_means_all.drop(
    columns=["wichtn"],
    errors="ignore"
)

valid_cluster_means_all = valid_cluster_means_all.drop(
    columns=["wichtn"],
    errors="ignore"
)

print(
    "Gefundene Mittelwertspalten:",
    f"Discovery={disc_cluster_means_all.shape[1]},",
    f"Validation={valid_cluster_means_all.shape[1]}"
)

print("\nErste Mittelwertspalten:")
print(disc_cluster_means_all.columns[:20].tolist())
# ============================================================
# 3. Gemeinsame Profilvariablen bestimmen
# ============================================================

common_variables = [
    variable
    for variable in profile_variables
    if variable in disc_cluster_means_all.columns
    and variable in valid_cluster_means_all.columns
    and variable in data_discov_full.data.columns
]

disc_cluster_means_all = (
    disc_cluster_means_all[common_variables]
    .copy()
)

valid_cluster_means_all = (
    valid_cluster_means_all[common_variables]
    .copy()
)

print(
    f"In beiden Cluster-Summaries vorhanden: "
    f"{len(common_variables)} Variablen"
)


# ============================================================
# 4. Discovery-Personendaten vorbereiten
# ============================================================

def series_to_numeric(series):
    """
    Konvertiert numerische und kategoriale Variablen robust
    in numerische Werte.

    Bei pandas-Categorical-Variablen werden zunächst die
    dargestellten Kategorien verwendet. Falls diese nicht
    numerisch sind, werden die geordneten Kategoriecodes genutzt.
    """
    if isinstance(series.dtype, pd.CategoricalDtype):
        category_values = pd.to_numeric(
            series.astype(str),
            errors="coerce"
        )

        # Numerisch beschriftete Kategorien, z. B. "1", "2", "3"
        if category_values.notna().any():
            return category_values

        # Nicht numerisch beschriftete ordinale Kategorien
        if series.cat.ordered:
            codes = series.cat.codes.astype(float)
            return codes.where(codes >= 0, np.nan)

        return pd.Series(np.nan, index=series.index, dtype=float)

    return pd.to_numeric(series, errors="coerce")


disc_person_data = pd.DataFrame(
    {
        variable: series_to_numeric(
            data_discov_full.data[variable]
        )
        for variable in common_variables
    },
    index=data_discov_full.data.index
)

disc_weights = np.asarray(
    sample_weight_discov,
    dtype=float
)

if len(disc_person_data) != len(disc_weights):
    raise ValueError(
        "Discovery-Personendaten und Gewichte haben "
        "unterschiedliche Längen."
    )


# ============================================================
# 5. Gewichteten Discovery-Mittelwert und gewichtete SD
#    für jede Variable berechnen
# ============================================================

def weighted_mean_sd_safe(data, weights):
    """
    Berechnet pro Variable den gewichteten Mittelwert und
    die gewichtete Populationsstandardabweichung.

    Fehlende Werte sowie nicht positive oder ungültige
    Gewichte werden ausgeschlossen.
    """
    weights = np.asarray(weights, dtype=float)

    means = {}
    standard_deviations = {}
    excluded = {}

    for variable in data.columns:
        values = pd.to_numeric(
            data[variable],
            errors="coerce"
        ).to_numpy(dtype=float)

        valid = (
            np.isfinite(values)
            & np.isfinite(weights)
            & (weights > 0)
        )

        x = values[valid]
        w = weights[valid]

        if len(x) == 0 or w.sum() <= 0:
            means[variable] = np.nan
            standard_deviations[variable] = np.nan
            excluded[variable] = (
                "keine gültigen Werte mit positivem Gewicht"
            )
            continue

        mean = np.average(
            x,
            weights=w
        )

        variance = np.average(
            (x - mean) ** 2,
            weights=w
        )

        sd = np.sqrt(variance)

        means[variable] = mean
        standard_deviations[variable] = sd

        if not np.isfinite(sd):
            excluded[variable] = "SD nicht definiert"
        elif sd == 0:
            excluded[variable] = "keine Varianz"

    return (
        pd.Series(means, dtype=float),
        pd.Series(standard_deviations, dtype=float),
        excluded
    )


discovery_mean, discovery_sd, excluded_variables = (
    weighted_mean_sd_safe(
        disc_person_data,
        disc_weights
    )
)

print("\nVariablen ohne verwendbare Discovery-SD:")

if excluded_variables:
    display(
        pd.Series(
            excluded_variables,
            name="Grund"
        ).to_frame()
    )
else:
    print("Keine")


# ============================================================
# 6. Nur Variablen mit gültiger positiver Discovery-SD behalten
# ============================================================

usable_variables = [
    variable
    for variable in common_variables
    if pd.notna(discovery_mean[variable])
    and pd.notna(discovery_sd[variable])
    and np.isfinite(discovery_sd[variable])
    and discovery_sd[variable] > 0
]

print(f"\nVerwendete Variablen: {len(usable_variables)}")
print(
    f"Entfernte Variablen: "
    f"{len(common_variables) - len(usable_variables)}"
)

if len(usable_variables) < 3:
    raise ValueError(
        "Für den Profilvergleich sind weniger als drei "
        "verwendbare Variablen vorhanden."
    )


# ============================================================
# 7. Clustergrößen bestimmen
# ============================================================

labels_discov_series = (
    pd.Series(labels_discov)
    .reset_index(drop=True)
)

labels_valid_series = (
    pd.Series(labels_valid)
    .reset_index(drop=True)
)

disc_cluster_counts = (
    labels_discov_series
    .value_counts()
    .sort_index()
)

valid_cluster_counts = (
    labels_valid_series
    .value_counts()
    .sort_index()
)

min_cluster_size = 100

large_disc_clusters = (
    disc_cluster_counts
    .loc[lambda counts: counts >= min_cluster_size]
    .index
    .tolist()
)

large_valid_clusters = (
    valid_cluster_counts
    .loc[lambda counts: counts >= min_cluster_size]
    .index
    .tolist()
)

print("\nClustergrößen Discovery:")
display(
    disc_cluster_counts
    .rename("n")
    .to_frame()
)

print("Clustergrößen Validation:")
display(
    valid_cluster_counts
    .rename("n")
    .to_frame()
)

print(
    f"Discovery-Cluster mit mindestens "
    f"{min_cluster_size} Personen:"
)
print(large_disc_clusters)

print(
    f"Validation-Cluster mit mindestens "
    f"{min_cluster_size} Personen:"
)
print(large_valid_clusters)


# ============================================================
# 8. Funktion für Standardisierung und Spearman-Vergleich
# ============================================================

def compare_cluster_profiles(
    disc_cluster_means,
    valid_cluster_means,
    usable_variables,
    discovery_mean,
    discovery_sd,
    title
):
    """
    Standardisiert Discovery- und Validation-Clusterprofile
    anhand der gewichteten Discovery-Gesamtmittelwerte und
    -standardabweichungen und berechnet anschließend die
    Spearman-Korrelationen zwischen allen Profilpaaren.
    """

    if disc_cluster_means.empty:
        raise ValueError(
            f"{title}: Keine Discovery-Cluster vorhanden."
        )

    if valid_cluster_means.empty:
        raise ValueError(
            f"{title}: Keine Validation-Cluster vorhanden."
        )

    # Clusterprofile anhand derselben Discovery-Skala standardisieren
    disc_profiles_z = (
        disc_cluster_means[usable_variables]
        - discovery_mean[usable_variables]
    ) / discovery_sd[usable_variables]

    valid_profiles_z = (
        valid_cluster_means[usable_variables]
        - discovery_mean[usable_variables]
    ) / discovery_sd[usable_variables]

    print("\n" + "=" * 70)
    print(title)
    print("=" * 70)

    print("\nStandardisierte Discovery-Clusterprofile:")
    display(disc_profiles_z.round(3))

    print("Standardisierte Validation-Clusterprofile:")
    display(valid_profiles_z.round(3))

    # Leere Ergebnismatrizen
    spearman_matrix = pd.DataFrame(
        index=[
            f"Discovery {cluster}"
            for cluster in disc_profiles_z.index
        ],
        columns=[
            f"Validation {cluster}"
            for cluster in valid_profiles_z.index
        ],
        dtype=float
    )

    p_value_matrix = spearman_matrix.copy()
    n_variables_matrix = spearman_matrix.copy()

    # Profilkorrelationen berechnen
    for discovery_cluster in disc_profiles_z.index:
        for validation_cluster in valid_profiles_z.index:

            discovery_profile = disc_profiles_z.loc[
                discovery_cluster
            ]

            validation_profile = valid_profiles_z.loc[
                validation_cluster
            ]

            # Nur Variablen verwenden, die in beiden Profilen gültig sind
            complete = (
                discovery_profile.notna()
                & validation_profile.notna()
            )

            x = discovery_profile.loc[complete]
            y = validation_profile.loc[complete]

            row_name = f"Discovery {discovery_cluster}"
            column_name = f"Validation {validation_cluster}"

            n_variables_matrix.loc[
                row_name,
                column_name
            ] = len(x)

            if (
                len(x) < 3
                or x.nunique() < 2
                or y.nunique() < 2
            ):
                rho = np.nan
                p_value = np.nan
            else:
                rho, p_value = spearmanr(x, y)

            spearman_matrix.loc[
                row_name,
                column_name
            ] = rho

            p_value_matrix.loc[
                row_name,
                column_name
            ] = p_value

    print("\nSpearman-Ähnlichkeitsmatrix der Clusterprofile:")
    display(spearman_matrix.round(3))

    print("p-Wert-Matrix:")
    display(p_value_matrix.round(4))

    print("Anzahl der jeweils verwendeten Variablen:")
    display(n_variables_matrix.astype("Int64"))

    return {
        "disc_profiles_z": disc_profiles_z,
        "valid_profiles_z": valid_profiles_z,
        "spearman_matrix": spearman_matrix,
        "p_value_matrix": p_value_matrix,
        "n_variables_matrix": n_variables_matrix
    }


# ============================================================
# 9. Vergleich 1: Alle Cluster
# ============================================================

results_all_clusters = compare_cluster_profiles(
    disc_cluster_means=disc_cluster_means_all,
    valid_cluster_means=valid_cluster_means_all,
    usable_variables=usable_variables,
    discovery_mean=discovery_mean,
    discovery_sd=discovery_sd,
    title="Profilvergleich: alle Cluster"
)


# ============================================================
# 10. Vergleich 2: Nur Cluster mit mindestens 100 Personen
# ============================================================

# Sicherstellen, dass die ausgewählten Cluster auch im
# Index der gespeicherten Summary-Tabellen vorhanden sind
large_disc_clusters_available = [
    cluster
    for cluster in large_disc_clusters
    if cluster in disc_cluster_means_all.index
]

large_valid_clusters_available = [
    cluster
    for cluster in large_valid_clusters
    if cluster in valid_cluster_means_all.index
]

missing_disc_clusters = sorted(
    set(large_disc_clusters)
    - set(large_disc_clusters_available)
)

missing_valid_clusters = sorted(
    set(large_valid_clusters)
    - set(large_valid_clusters_available)
)

if missing_disc_clusters:
    print(
        "Warnung: Folgende ausreichend große Discovery-Cluster "
        "fehlen in den Summary-Tabellen:"
    )
    print(missing_disc_clusters)

if missing_valid_clusters:
    print(
        "Warnung: Folgende ausreichend große Validation-Cluster "
        "fehlen in den Summary-Tabellen:"
    )
    print(missing_valid_clusters)

disc_cluster_means_100 = (
    disc_cluster_means_all
    .loc[large_disc_clusters_available]
    .copy()
)

valid_cluster_means_100 = (
    valid_cluster_means_all
    .loc[large_valid_clusters_available]
    .copy()
)

results_clusters_100 = compare_cluster_profiles(
    disc_cluster_means=disc_cluster_means_100,
    valid_cluster_means=valid_cluster_means_100,
    usable_variables=usable_variables,
    discovery_mean=discovery_mean,
    discovery_sd=discovery_sd,
    title=(
        f"Profilvergleich: nur Cluster mit mindestens "
        f"{min_cluster_size} Personen"
    )
)

Laut Metadaten ausgewählt: 39 kontinuierliche/ordinale Variablen
Gefundene Mittelwertspalten: Discovery=106, Validation=106

Erste Mittelwertspalten:
['zeit', 'ges', 'alter', 'altq', 'hh', 'hh14', 'allein', 'hne', 'vx210', 'wein30gr', 'mish30gr', 'bier30gr', 'audit', 'bierkons', 'weinkons', 'spirkons', 'mishkons', 'binge', 'alk30gr', 'alk30kat']
In beiden Cluster-Summaries vorhanden: 38 Variablen

Variablen ohne verwendbare Discovery-SD:

                                                  Grund
audit                                     keine Varianz
fag_sch                                   keine Varianz
psecdi_sch   keine gültigen Werte mit positivem Gewicht
hnb_fag_sch  keine gültigen Werte mit positivem Gewicht
sds_c        keine gültigen Werte mit positivem Gewicht
sds_k        keine gültigen Werte mit positivem Gewicht
sds_a        keine gültigen Werte mit positivem Gewicht
fr12_meth1                                keine Varianz
pomi         keine gültigen Werte mit positivem Gewicht

Verwendete Variablen: 29
Entfernte Variablen: 9

Clustergrößen Discovery:

          n
label
0       711
1       263
2      3119
3         1
4       194
5         8
6        20
7      1526
8        65
9         2
10        2
11       66
12      263
13       17
14        4
15      425
16      436
17        5
18       89
19        9
20        2
21      477
22     1131

Clustergrößen Validation:

          n
label
0       784
1      1056
2         1
3      1498
4        20
5         8
6        68
7       128
8       317
9       206
10     2062
11      351
12        1
13      218
14      628
15      104
16        3
17      661
18      274
19       88
20       79
21       32
22        1

Discovery-Cluster mit mindestens 100 Personen:
['0', '1', '2', '4', '7', '12', '15', '16', '21', '22']
Validation-Cluster mit mindestens 100 Personen:
['0', '1', '3', '7', '8', '9', '10', '11', '13', '14', '15', '17', '18']

======================================================================
Profilvergleich: alle Cluster
======================================================================

Standardisierte Discovery-Clusterprofile:

,alter,altq,hh,hh14,hne,vx210,wein30gr,mish30gr,bier30gr,binge,...,fr12_nps1,fr12_au1,anr_kat,app_kat,anab_kat,schm_kat,schl_kat,ber_kat,depr_kat,neur_kat
cluster,,,,,,,,,,,,,,,,,,,,,
0,0.150,-1.163,-0.076,-0.009,-0.295,0.556,0.059,-0.024,0.282,-1.243,...,-13.585,-5.675,-0.083,-0.036,-0.044,-0.121,-0.164,-0.137,-0.207,-0.099
1,-0.481,-1.810,0.005,0.029,-0.422,0.134,0.262,0.140,0.213,-1.434,...,-13.585,-5.675,-0.083,-0.036,-0.044,0.012,-0.164,-0.137,-0.179,-0.099
2,0.166,-1.171,0.055,0.064,-0.047,0.556,0.014,-0.098,-0.133,-1.836,...,-13.585,-5.675,-0.083,-0.036,-0.044,-0.175,-0.164,-0.137,-0.207,-0.099
3,-0.791,-1.722,-0.598,-0.569,-2.931,-0.687,-0.434,-0.222,-0.457,-2.120,...,-13.585,16.689,-0.083,-0.036,-0.044,1.496,-0.164,-0.137,-0.207,-0.099
4,0.367,-0.973,-0.146,-0.170,-0.818,-0.250,-0.083,-0.140,-0.140,-1.759,...,-13.585,-5.675,-0.083,-0.036,-0.044,0.754,1.843,2.841,1.869,1.997
5,-1.279,-2.517,-0.633,-0.494,-0.456,0.479,1.043,2.436,0.805,-0.798,...,-13.585,-0.479,4.273,-0.036,-0.044,0.018,1.931,-0.137,-0.207,-0.099
6,-0.906,-2.250,-0.353,-0.327,-0.666,0.389,0.354,1.438,-0.161,-0.597,...,-10.137,-4.187,1.309,23.410,0.720,0.837,1.120,0.274,0.222,0.164
7,-0.104,-1.420,0.106,0.116,-0.525,-1.444,-0.434,-0.222,-0.457,-2.120,...,-13.585,-5.675,-0.083,-0.036,-0.044,-0.336,-0.164,-0.137,-0.207,-0.099
8,-0.490,-1.846,-0.104,-0.397,-0.287,0.026,-0.097,0.490,0.094,-1.216,...,-13.317,-5.369,9.386,-0.036,-0.044,0.307,0.095,0.324,0.534,0.347
9,0.392,-1.178,-1.071,-0.569,-1.898,-1.475,-0.246,-0.222,-0.384,-1.828,...,-8.623,5.507,-0.083,-0.036,-0.044,0.324,0.376,-0.137,-0.207,-0.099
10,0.368,-1.140,-0.038,0.487,-2.380,-1.618,-0.421,-0.183,-0.396,-1.920,...,-13.585,-5.675,13.550,-0.036,-0.044,2.669,8.684,9.612,4.315,10.695
11,-0.677,-2.039,-0.253,-0.282,-0.556,0.422,1.960,1.376,1.271,-0.350,...,-11.120,-1.634,0.043,-0.036,-0.044,0.446,1.274,0.624,0.400,0.292
12,-0.695,-2.035,-0.106,-0.070,-0.610,0.225,-0.003,0.248,0.231,-1.124,...,-13.314,-4.959,-0.083,-0.036,-0.044,0.030,-0.066,-0.116,-0.025,-0.099
13,-0.341,-1.561,0.025,-0.130,-0.954,-0.004,-0.347,-0.023,-0.044,-1.448,...,-13.585,-5.675,0.146,-0.036,18.530,0.701,0.655,-0.066,-0.207,0.674
14,-1.348,-2.669,-0.708,-0.569,-1.706,0.556,2.100,1.119,2.549,-0.276,...,-13.585,-1.251,-0.083,-0.036,1.929,0.001,-0.164,-0.137,-0.207,-0.099
15,-0.154,-1.526,-0.146,-0.263,-0.332,0.366,0.874,1.156,1.204,-0.669,...,-13.585,-5.675,-0.083,-0.036,-0.044,0.199,0.972,0.224,-0.196,-0.006
16,0.134,-1.209,-0.100,-0.093,-0.332,0.556,0.067,0.030,0.116,-1.372,...,-13.585,-5.675,-0.083,-0.036,-0.044,0.919,-0.110,-0.137,1.135,-0.099
17,-0.720,-2.056,-0.816,-0.071,-1.526,0.216,-0.036,-0.130,0.608,-1.020,...,-13.585,10.543,2.577,-0.036,-0.044,0.956,0.934,0.508,1.514,3.494
18,-0.061,-1.398,-0.377,-0.266,-0.766,0.012,0.100,0.187,-0.125,-1.374,...,-13.341,-5.675,-0.083,-0.036,-0.044,0.964,2.052,1.598,1.407,1.556
19,0.205,-0.971,-0.462,-0.569,-1.071,0.291,-0.217,0.305,0.313,-1.128,...,-13.585,-5.675,-0.083,-0.036,-0.044,2.405,7.430,6.942,4.006,3.600
20,-1.405,-2.540,-1.088,-0.569,0.011,0.556,-0.140,0.332,2.723,1.076,...,-12.032,16.689,-0.083,-0.036,-0.044,-0.849,-0.164,-0.137,-0.207,-0.099
21,0.055,-1.259,-0.070,-0.076,-0.740,-1.373,-0.434,-0.222,-0.457,-2.120,...,-13.585,-5.675,-0.083,-0.036,-0.044,0.398,-0.164,-0.137,0.383,-0.099
22,-0.164,-1.505,0.018,-0.053,-0.190,0.556,0.380,0.182,0.531,-0.757,...,-13.585,-5.675,-0.083,-0.036,-0.044,0.005,-0.164,-0.137,-0.207,-0.099
23,0.000,-1.331,0.000,0.000,-0.315,0.000,0.000,0.000,0.000,-1.598,...,-13.550,-5.591,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000

Standardisierte Validation-Clusterprofile:

,alter,altq,hh,hh14,hne,vx210,wein30gr,mish30gr,bier30gr,binge,...,fr12_nps1,fr12_au1,anr_kat,app_kat,anab_kat,schm_kat,schl_kat,ber_kat,depr_kat,neur_kat
cluster,,,,,,,,,,,,,,,,,,,,,
0,-0.401,-1.710,-0.049,-0.098,-0.072,0.131,0.075,0.032,0.474,-1.245,...,-13.585,-5.675,-0.083,-0.036,-0.044,-0.627,-0.164,-0.137,-0.207,-0.099
1,-0.131,-1.420,0.100,0.154,-0.327,-1.667,-0.434,-0.222,-0.457,-2.120,...,-13.585,-5.675,-0.083,-0.036,-0.044,-0.528,-0.164,-0.137,-0.207,-0.099
2,-0.551,-1.722,-1.345,-0.569,-2.301,0.556,-0.434,-0.222,-0.192,-0.522,...,-0.035,-5.675,-0.083,-0.036,-0.044,0.324,5.735,6.362,4.963,-0.099
3,0.030,-1.268,0.049,0.125,0.087,0.097,0.140,-0.024,-0.139,-1.757,...,-13.585,-5.675,-0.083,-0.036,-0.044,0.548,-0.164,-0.137,-0.207,-0.099
4,-0.505,-1.721,-0.454,-0.109,-1.212,-0.506,0.693,0.094,0.114,-1.086,...,-13.585,-5.675,0.528,28.724,0.380,0.598,0.793,1.137,0.382,1.365
5,-0.276,-1.467,-0.737,-0.202,-1.933,-1.010,-0.323,-0.129,-0.407,-1.504,...,-13.585,-5.675,-0.083,-0.036,22.906,0.652,0.042,-0.137,2.313,0.152
6,-0.347,-1.661,-0.256,-0.331,-0.372,-0.024,0.446,0.059,0.399,-1.258,...,-13.255,-5.675,9.453,-0.036,-0.044,0.607,0.504,0.918,0.651,0.761
7,-0.373,-1.666,0.012,-0.064,-0.494,-0.138,0.195,0.220,0.278,-1.185,...,-13.585,-5.675,-0.083,-0.036,-0.044,0.048,-0.098,-0.137,-0.161,-0.099
8,-0.505,-1.794,-0.261,-0.222,-0.457,0.291,0.324,0.341,0.633,-1.068,...,-13.585,-5.675,-0.083,-0.036,-0.044,0.011,0.359,-0.137,-0.080,-0.099
9,-0.790,-2.092,-0.253,-0.297,-0.442,0.314,0.431,0.552,0.550,-0.901,...,-12.756,-5.675,-0.083,-0.036,-0.044,0.032,0.140,0.084,0.036,0.044
10,0.191,-1.123,-0.013,0.010,0.060,0.556,-0.010,-0.098,-0.123,-1.791,...,-13.585,-5.675,-0.083,-0.036,-0.044,-0.612,-0.164,-0.137,-0.207,-0.099
11,0.295,-1.012,-0.153,-0.040,-0.348,-0.030,0.237,-0.043,0.359,-1.432,...,-13.585,-5.675,-0.083,-0.036,-0.044,0.530,-0.148,-0.137,0.470,-0.046
12,-1.190,-2.388,0.150,-0.569,-2.616,0.556,0.594,-0.222,-0.258,1.076,...,NaN,-5.675,-0.083,-0.036,-0.044,-0.849,-0.164,-0.137,-0.207,-0.099
13,0.436,-0.930,-0.252,-0.306,-0.428,-0.263,0.289,0.147,0.034,-1.556,...,-13.585,-5.675,-0.083,-0.036,-0.044,0.803,3.898,2.227,1.167,0.906
14,0.283,-1.033,-0.184,-0.145,-0.296,-0.261,-0.114,-0.117,-0.253,-1.858,...,-13.585,-5.675,-0.083,-0.036,-0.044,0.878,0.008,-0.137,1.078,0.629
15,-0.310,-1.614,0.231,0.062,-0.214,-0.048,-0.113,0.155,0.209,-1.305,...,-13.585,-5.675,-0.083,-0.036,-0.044,-0.087,-0.164,-0.137,-0.207,-0.099
16,-1.725,-3.515,0.068,-0.569,-0.397,0.174,-0.299,-0.120,-0.353,-1.013,...,-7.948,-5.675,-0.083,-0.036,-0.044,-0.129,0.741,0.860,-0.207,-0.099
17,0.096,-1.198,-0.107,0.019,-0.221,0.074,-0.024,-0.005,0.249,-1.415,...,-13.585,-5.675,-0.083,-0.036,-0.044,-0.229,-0.164,-0.137,-0.207,-0.099
18,-0.225,-1.576,-0.141,-0.162,-0.122,0.533,1.505,1.193,2.211,-0.131,...,-13.585,-5.675,-0.083,-0.036,-0.044,0.175,-0.146,-0.137,0.350,-0.099
19,0.037,-1.313,-0.313,-0.195,-0.747,-0.226,0.580,0.177,0.671,-1.284,...,-13.419,-5.675,-0.083,-0.036,-0.044,0.864,1.673,1.508,1.447,1.479
20,0.125,-1.197,-0.228,-0.288,-0.526,0.019,0.277,0.103,0.377,-1.390,...,-11.634,-5.675,-0.083,-0.036,-0.044,0.838,2.029,3.663,1.360,0.676
21,0.276,-1.141,-0.529,-0.381,-0.815,-0.491,-0.121,-0.108,-0.280,-1.766,...,-13.585,-5.675,-0.083,-0.036,-0.044,1.187,3.110,2.236,2.225,1.476
22,0.807,-0.391,-1.345,-0.569,-2.931,0.556,-0.434,-0.222,1.533,1.076,...,NaN,-5.675,-0.083,-0.036,-0.044,2.669,-0.164,3.113,-0.207,-0.099
23,0.010,-1.297,-0.054,-0.014,-0.160,-0.056,0.051,0.000,0.061,-1.609,...,-13.540,-5.675,-0.017,0.070,-0.006,-0.037,0.056,0.015,0.051,0.036

Spearman-Ähnlichkeitsmatrix der Clusterprofile:

,Validation 0,Validation 1,Validation 2,Validation 3,Validation 4,Validation 5,Validation 6,Validation 7,Validation 8,Validation 9,...,Validation 14,Validation 15,Validation 16,Validation 17,Validation 18,Validation 19,Validation 20,Validation 21,Validation 22,Validation 23
Discovery 0,0.854,0.599,0.217,0.747,0.643,0.629,0.639,0.881,0.755,0.736,...,0.563,0.808,0.434,0.986,0.759,0.708,0.659,0.603,0.306,0.728
Discovery 1,0.874,0.579,0.242,0.748,0.719,0.666,0.722,0.966,0.812,0.798,...,0.562,0.859,0.473,0.908,0.829,0.754,0.688,0.614,0.270,0.738
Discovery 2,0.840,0.745,0.149,0.903,0.574,0.538,0.541,0.674,0.518,0.544,...,0.655,0.811,0.404,0.799,0.702,0.506,0.578,0.533,0.065,0.656
Discovery 3,0.053,0.277,0.484,0.059,0.421,0.465,0.361,0.254,0.260,0.173,...,0.333,0.127,0.247,0.119,0.100,0.339,0.255,0.413,0.408,0.231
Discovery 4,0.526,0.800,0.403,0.583,0.909,0.932,0.875,0.648,0.569,0.566,...,0.923,0.573,0.595,0.612,0.580,0.911,0.891,0.988,0.302,0.811
Discovery 5,0.733,0.426,0.358,0.518,0.682,0.583,0.758,0.766,0.908,0.900,...,0.524,0.675,0.617,0.664,0.764,0.667,0.650,0.574,0.309,0.671
Discovery 6,0.759,0.666,0.464,0.668,0.856,0.817,0.814,0.822,0.758,0.722,...,0.753,0.773,0.625,0.700,0.796,0.762,0.756,0.779,0.285,0.777
Discovery 7,0.599,0.992,0.170,0.697,0.779,0.842,0.687,0.647,0.434,0.408,...,0.856,0.730,0.530,0.627,0.505,0.665,0.644,0.804,0.063,0.718
Discovery 8,0.678,0.654,0.489,0.565,0.853,0.841,0.953,0.762,0.707,0.733,...,0.779,0.705,0.595,0.669,0.772,0.873,0.855,0.854,0.330,0.766
Discovery 9,-0.052,0.208,-0.162,0.007,0.304,0.367,0.247,0.160,0.285,0.230,...,0.298,-0.001,0.248,0.121,-0.010,0.297,0.223,0.363,-0.059,0.207
Discovery 10,0.491,0.853,0.365,0.547,0.882,0.916,0.878,0.646,0.534,0.516,...,0.875,0.601,0.591,0.604,0.508,0.849,0.798,0.938,0.263,0.744
Discovery 11,0.781,0.441,0.451,0.584,0.772,0.644,0.832,0.865,0.918,0.948,...,0.584,0.723,0.583,0.753,0.837,0.848,0.833,0.687,0.392,0.796
Discovery 12,0.759,0.406,0.365,0.591,0.604,0.588,0.666,0.819,0.968,0.951,...,0.514,0.730,0.592,0.751,0.804,0.670,0.661,0.543,0.412,0.678
Discovery 13,0.653,0.770,0.373,0.655,0.817,0.883,0.803,0.759,0.652,0.597,...,0.801,0.751,0.681,0.660,0.638,0.767,0.737,0.826,0.265,0.665
Discovery 14,0.715,0.319,0.243,0.467,0.605,0.523,0.623,0.750,0.726,0.745,...,0.430,0.655,0.392,0.675,0.760,0.612,0.600,0.479,0.243,0.634
Discovery 15,0.870,0.526,0.425,0.665,0.789,0.667,0.813,0.907,0.848,0.867,...,0.626,0.820,0.527,0.856,0.865,0.852,0.853,0.711,0.366,0.841
Discovery 16,0.722,0.544,0.369,0.721,0.695,0.763,0.751,0.819,0.745,0.715,...,0.724,0.712,0.419,0.833,0.813,0.789,0.782,0.731,0.350,0.745
Discovery 17,0.376,0.376,0.295,0.269,0.643,0.605,0.733,0.502,0.676,0.655,...,0.533,0.388,0.523,0.434,0.476,0.660,0.615,0.609,0.273,0.544
Discovery 18,0.617,0.641,0.514,0.601,0.903,0.866,0.912,0.726,0.699,0.735,...,0.828,0.611,0.619,0.655,0.700,0.956,0.943,0.937,0.321,0.817
Discovery 19,0.628,0.616,0.548,0.546,0.861,0.833,0.905,0.732,0.717,0.739,...,0.797,0.649,0.586,0.687,0.707,0.960,0.966,0.914,0.398,0.838
Discovery 20,0.587,0.158,0.069,0.276,0.298,0.185,0.348,0.426,0.606,0.632,...,0.169,0.476,0.299,0.435,0.606,0.289,0.323,0.165,0.213,0.406
Discovery 21,0.492,0.862,0.216,0.653,0.788,0.926,0.721,0.695,0.513,0.443,...,0.866,0.609,0.516,0.643,0.509,0.772,0.699,0.878,0.211,0.691
Discovery 22,0.947,0.589,0.310,0.842,0.676,0.570,0.697,0.870,0.729,0.761,...,0.628,0.945,0.426,0.837,0.915,0.645,0.727,0.557,0.257,0.768
Discovery 23,0.824,0.829,0.372,0.797,0.871,0.871,0.870,0.871,0.736,0.735,...,0.862,0.861,0.588,0.867,0.800,0.872,0.873,0.872,0.281,0.873

p-Wert-Matrix:

,Validation 0,Validation 1,Validation 2,Validation 3,Validation 4,Validation 5,Validation 6,Validation 7,Validation 8,Validation 9,...,Validation 14,Validation 15,Validation 16,Validation 17,Validation 18,Validation 19,Validation 20,Validation 21,Validation 22,Validation 23
Discovery 0,0.0000,0.0006,0.2576,0.0000,0.0002,0.0003,0.0002,0.0000,0.0000,0.0000,...,0.0015,0.0000,0.0185,0.0000,0.0000,0.0000,0.0001,0.0005,0.1133,0.0000
Discovery 1,0.0000,0.0010,0.2062,0.0000,0.0000,0.0001,0.0000,0.0000,0.0000,0.0000,...,0.0015,0.0000,0.0096,0.0000,0.0000,0.0000,0.0000,0.0004,0.1640,0.0000
Discovery 2,0.0000,0.0000,0.4412,0.0000,0.0011,0.0026,0.0024,0.0001,0.0040,0.0023,...,0.0001,0.0000,0.0298,0.0000,0.0000,0.0051,0.0010,0.0029,0.7440,0.0001
Discovery 3,0.7860,0.1452,0.0078,0.7607,0.0231,0.0111,0.0547,0.1842,0.1738,0.3697,...,0.0771,0.5112,0.1959,0.5396,0.6058,0.0721,0.1824,0.0260,0.0310,0.2289
Discovery 4,0.0034,0.0000,0.0300,0.0009,0.0000,0.0000,0.0000,0.0001,0.0013,0.0014,...,0.0000,0.0012,0.0007,0.0004,0.0010,0.0000,0.0000,0.0000,0.1188,0.0000
Discovery 5,0.0000,0.0212,0.0568,0.0040,0.0000,0.0009,0.0000,0.0000,0.0000,0.0000,...,0.0035,0.0001,0.0004,0.0001,0.0000,0.0001,0.0001,0.0011,0.1100,0.0001
Discovery 6,0.0000,0.0001,0.0112,0.0001,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0003,0.0000,0.0000,0.0000,0.0000,0.0000,0.1413,0.0000
Discovery 7,0.0006,0.0000,0.3781,0.0000,0.0000,0.0000,0.0000,0.0001,0.0187,0.0279,...,0.0000,0.0000,0.0031,0.0003,0.0052,0.0001,0.0002,0.0000,0.7503,0.0000
Discovery 8,0.0001,0.0001,0.0071,0.0014,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0007,0.0001,0.0000,0.0000,0.0000,0.0000,0.0863,0.0000
Discovery 9,0.7879,0.2780,0.4024,0.9697,0.1089,0.0505,0.1968,0.4082,0.1337,0.2310,...,0.1170,0.9960,0.1941,0.5329,0.9575,0.1176,0.2446,0.0529,0.7651,0.2804
Discovery 10,0.0068,0.0000,0.0519,0.0021,0.0000,0.0000,0.0000,0.0002,0.0028,0.0041,...,0.0000,0.0006,0.0007,0.0005,0.0049,0.0000,0.0000,0.0000,0.1759,0.0000
Discovery 11,0.0000,0.0167,0.0140,0.0009,0.0000,0.0002,0.0000,0.0000,0.0000,0.0000,...,0.0009,0.0000,0.0009,0.0000,0.0000,0.0000,0.0000,0.0000,0.0392,0.0000
Discovery 12,0.0000,0.0289,0.0519,0.0007,0.0005,0.0008,0.0001,0.0000,0.0000,0.0000,...,0.0044,0.0000,0.0007,0.0000,0.0000,0.0001,0.0001,0.0023,0.0293,0.0001
Discovery 13,0.0001,0.0000,0.0460,0.0001,0.0000,0.0000,0.0000,0.0000,0.0001,0.0006,...,0.0000,0.0000,0.0000,0.0001,0.0002,0.0000,0.0000,0.0000,0.1731,0.0001
Discovery 14,0.0000,0.0914,0.2043,0.0106,0.0005,0.0036,0.0003,0.0000,0.0000,0.0000,...,0.0199,0.0001,0.0354,0.0001,0.0000,0.0004,0.0006,0.0086,0.2127,0.0002
Discovery 15,0.0000,0.0034,0.0217,0.0001,0.0000,0.0001,0.0000,0.0000,0.0000,0.0000,...,0.0003,0.0000,0.0033,0.0000,0.0000,0.0000,0.0000,0.0000,0.0557,0.0000
Discovery 16,0.0000,0.0023,0.0486,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0238,0.0000,0.0000,0.0000,0.0000,0.0000,0.0676,0.0000
Discovery 17,0.0442,0.0442,0.1202,0.1575,0.0002,0.0005,0.0000,0.0055,0.0001,0.0001,...,0.0029,0.0377,0.0036,0.0185,0.0091,0.0001,0.0004,0.0005,0.1605,0.0023
Discovery 18,0.0004,0.0002,0.0043,0.0006,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0004,0.0003,0.0001,0.0000,0.0000,0.0000,0.0000,0.0961,0.0000
Discovery 19,0.0003,0.0004,0.0021,0.0022,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0001,0.0008,0.0000,0.0000,0.0000,0.0000,0.0000,0.0357,0.0000
Discovery 20,0.0008,0.4141,0.7222,0.1467,0.1170,0.3361,0.0645,0.0213,0.0005,0.0002,...,0.3795,0.0091,0.1151,0.0184,0.0005,0.1282,0.0873,0.3923,0.2767,0.0289
Discovery 21,0.0067,0.0000,0.2610,0.0001,0.0000,0.0000,0.0000,0.0000,0.0044,0.0161,...,0.0000,0.0005,0.0042,0.0002,0.0048,0.0000,0.0000,0.0000,0.2805,0.0000
Discovery 22,0.0000,0.0008,0.1013,0.0000,0.0001,0.0012,0.0000,0.0000,0.0000,0.0000,...,0.0003,0.0000,0.0212,0.0000,0.0000,0.0002,0.0000,0.0017,0.1873,0.0000
Discovery 23,0.0000,0.0000,0.0471,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0008,0.0000,0.0000,0.0000,0.0000,0.0000,0.1480,0.0000

Anzahl der jeweils verwendeten Variablen:

,Validation 0,Validation 1,Validation 2,Validation 3,Validation 4,Validation 5,Validation 6,Validation 7,Validation 8,Validation 9,...,Validation 14,Validation 15,Validation 16,Validation 17,Validation 18,Validation 19,Validation 20,Validation 21,Validation 22,Validation 23
Discovery 0,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 1,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 2,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 3,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 4,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 5,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 6,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 7,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 8,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 9,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 10,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 11,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 12,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 13,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 14,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 15,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 16,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 17,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 18,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 19,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 20,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 21,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 22,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29
Discovery 23,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,28,29

Warnung: Folgende ausreichend große Discovery-Cluster fehlen in den Summary-Tabellen:
['0', '1', '12', '15', '16', '2', '21', '22', '4', '7']
Warnung: Folgende ausreichend große Validation-Cluster fehlen in den Summary-Tabellen:
['0', '1', '10', '11', '13', '14', '15', '17', '18', '3', '7', '8', '9']

ValueError: Profilvergleich: nur Cluster mit mindestens 100 Personen: Keine Discovery-Cluster vorhanden.